# Generated by Django 4.0.3 on 2022-06-09 03:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PEI', '0002_rename_title_product_model_alter_product_brand'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='inCart',
            field=models.BooleanField(default=False),
        ),
    ]
