# Generated by Django 4.0.3 on 2022-06-09 03:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PEI', '0003_product_incart'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='inCart',
            field=models.IntegerField(default=0),
        ),
    ]
